# Generated by Django 4.0.1 on 2022-01-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStats',
            new_name='UserStat',
        ),
    ]
