# Generated by Django 4.0.1 on 2022-01-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_userstats_userstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='first_name',
            field=models.CharField(default='first', max_length=100),
        ),
        migrations.AddField(
            model_name='userstat',
            name='last_name',
            field=models.CharField(default='last', max_length=100),
        ),
        migrations.AddField(
            model_name='userstat',
            name='username',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
