# Generated by Django 4.0.1 on 2022-02-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userstat_first_name_userstat_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
