# Generated by Django 4.0.1 on 2022-02-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_songstat_track_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(default='none', max_length=200)),
                ('title', models.CharField(default='none', max_length=200)),
                ('img_url', models.CharField(default='none', max_length=200)),
                ('release_date', models.CharField(default='none', max_length=200)),
                ('duration', models.BigIntegerField()),
            ],
        ),
    ]
