# Generated by Django 4.0.1 on 2022-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_trackstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackstat',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
