# Generated by Django 4.0.1 on 2022-02-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_trackstat_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='songstat',
            name='img_url',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
