# Generated by Django 4.0.1 on 2022-02-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_trackstat_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackstat',
            name='snippet',
            field=models.URLField(),
        ),
    ]
