# Generated by Django 4.0.1 on 2022-02-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_trackstat_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackstat',
            name='snippet',
            field=models.URLField(default='none'),
        ),
    ]
