# Generated by Django 4.0.1 on 2022-02-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_chartstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstat',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
    ]
