# Generated by Django 4.0.1 on 2022-02-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_chartstat_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='spot_username',
            field=models.CharField(default='none', help_text='Spotify Username (this is how we access your data to give you personalized insights!', max_length=200),
        ),
    ]
