# Generated by Django 4.0.1 on 2022-02-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userstat_spot_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstat',
            old_name='spot_username',
            new_name='spotify_username',
        ),
    ]
