# Generated by Django 4.0.1 on 2022-03-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_userstat_spotify_username_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstat',
            name='track_id',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
