# Generated by Django 4.0.1 on 2022-03-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_chartstat_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
